name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t abhinayreddydocker/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true abhinayreddydocker/react-test npm test
 
      - run: docker build -t abhinayreddydocker/multi-client-28-12 ./client
      - run: docker build -t abhinayreddydocker/multi-nginx-28-12 ./nginx
      - run: docker build -t abhinayreddydocker/multi-server-28-12 ./server
      - run: docker build -t abhinayreddydocker/multi-worker-28-12 ./worker
 
      - run: docker push abhinayreddydocker/multi-client-28-12
      - run: docker push abhinayreddydocker/multi-nginx-28-12
      - run: docker push abhinayreddydocker/multi-server-28-12
      - run: docker push abhinayreddydocker/multi-worker-28-12 