name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t abhinayreddydocker/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true abhinayreddydocker/react-test npm test
 
      - run: docker build -t abhinayreddydocker/multi-client-28-12 ./client
      - run: docker build -t abhinayreddydocker/multi-nginx-28-12 ./nginx
      - run: docker build -t abhinayreddydocker/multi-server-28-12 ./server
      - run: docker build -t abhinayreddydocker/multi-worker-28-12 ./worker
 
      - run: docker push abhinayreddydocker/multi-client-28-12
      - run: docker push abhinayreddydocker/multi-nginx-28-12
      - run: docker push abhinayreddydocker/multi-server-28-12
      - run: docker push abhinayreddydocker/multi-worker-28-12 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: abhinayreddydocker/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multi-gh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-657561511210
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip